apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gcp-project-template
  description: Template for creating GCP projects using Terraform.
  tags:
    - template
    - terraform
    - gcp
spec:
  type: template
  owner: users
  path: ./gcp-project-template.yaml
