apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-deployment
  title: Deploy Terraform via GitLab Pipeline
  description: Trigger a GitLab pipeline to deploy a Terraform project
  tags:
    - terraform
    - gitlab
spec:
  owner: team@example.com
  type: service
  parameters:
    - title: Terraform Variables
      properties:
        parent:
          type: string
          title: Parent Organization (e.g., Organizations/123456)
        name:
          type: string
          title: Project Name
        project_id:
          type: string
          title: GitLab Project ID
          description: The numeric ID of the GitLab project
        branch:
          type: string
          title: Git Branch
          description: The branch in GitLab to trigger (e.g., main)
          default: main
        trigger_token:
          type: string
          title: Trigger Token
          description: Your GitLab pipeline trigger token
      required:
        - parent
        - name
        - project_id
        - branch
        - trigger_token
  steps:
    - id: deploy
      name: Trigger GitLab Pipeline
      action: gitlab:trigger-pipeline
      input:
        projectId: ${{ parameters.project_id }}
        branch: ${{ parameters.branch }}
        token: ${{ parameters.trigger_token }}
        variables:
          TF_VAR_parent: ${{ parameters.parent }}
          TF_VAR_name: ${{ parameters.name }}
