apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-deployment
  title: Deploy Terraform
  description: Trigger a GitLab pipeline to deploy a Terraform project with dynamic variables
  tags:
    - terraform
    - gitlab
spec:
  owner: users
  type: service
  parameters:
    - title: Terraform Deployment Parameters
      properties:
        parent:
          type: string
          title: Parent Organization (e.g., Organizations/123456)
          enum:
            - organizations/579983338372
        name:
          type: string
          title: Project Name
        billing_account:
          type: string
          title: Billing Account ID (e.g., 012345-678901-234567)
          enum:
            - 013BF1-64C8A0-B5CD6D
        branch:
          type: string
          title: Branch to trigger (e.g., main)
          enum:
            - main
            - develop
            - staging
            - production
        repoUrl:
          type: string
          title: GitLab Repository URL (e.g., https://gitlab.com/group/project)
          enum:
            - git.tmaws.io/public-cloud/tmp-livenation/infrastructure/gcp/project-creation-automation
            - gitlab.com/arth.muradyan/backstage-test/-/blob/main
        projectId:
          type: number
          title: GitLab Project ID
          enum:
            - 50811
            - 66242570
        tokenDescription:
          type: string
          title: Description of the Pipeline Token
          default: Backstage Pipeline Trigger
      required:
        - parent
        - name
        - billing_account
        - branch
        - repoUrl
        - projectId
        - tokenDescription
  steps:
    - id: trigger-pipeline
      name: Trigger GitLab Pipeline
      action: gitlab:pipeline:trigger
      input:
        repoUrl: ${{ parameters.repoUrl }}
        token: ${{ secrets.gitlab_token }}
        projectId: ${{ parameters.projectId }}
        branch: ${{ parameters.branch }}
        tokenDescription: ${{ parameters.tokenDescription }}
        variables:
          TF_VAR_parent: ${{ parameters.parent }}
          TF_VAR_name: ${{ parameters.name }}
          TF_VAR_billing_account: ${{ parameters.billing_account }}
