apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-gcp-project
  title: Create GCP Project (Terraform)
  description: Runs Terraform commands using built-in shell action
spec:
  owner: users
  type: service
  parameters:
    - title: GCP Project Information
      properties:
        project_id:
          title: Project ID
          description: GCP Project ID
          type: string
        project_name:
          title: Project Name
          description: Human-friendly name for the project
          type: string
        org_id:
          title: Organization ID
          description: GCP Organization ID
          type: string
        service_account_key:
          title: Service Account Key (JSON)
          description: Paste the full JSON key for your GCP service account.
          type: string
          format: password
      required:
        - project_id
        - project_name
        - org_id
        - service_account_key

  steps:
    - id: write-terraform-files
      name: Write Terraform Files
      action: shell
      input:
        commands:
          - |
            cat > main.tf <<EOF
            provider "google" {
              credentials = "${SERVICE_ACCOUNT_KEY}"
              project     = "${PROJECT_ID}"
            }

            resource "google_project" "default" {
              name       = "${PROJECT_NAME}"
              project_id = "${PROJECT_ID}"
              org_id     = "${ORG_ID}"
            }
            EOF
        env:
          PROJECT_ID: ${{ parameters.project_id }}
          PROJECT_NAME: ${{ parameters.project_name }}
          ORG_ID: ${{ parameters.org_id }}
          SERVICE_ACCOUNT_KEY: ${{ parameters.service_account_key }}

    - id: terraform-init
      name: Terraform Init
      action: shell
      input:
        commands:
          - terraform init

    - id: terraform-apply
      name: Terraform Apply
      action: shell
      input:
        commands:
          - terraform apply -auto-approve
