apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-gcp-project
  title: Create GCP Project (Terraform)
  description: Runs Terraform commands using built-in script-like actions
spec:
  owner: team
  type: service
  parameters:
    - title: GCP Project Information
      properties:
        project_id:
          title: Project ID
          type: string
        service_account_key:
          title: Service Account Key (JSON)
          type: string
          format: password
      required:
        - project_id
        - service_account_key

  steps:
    - id: write-terraform-files
      name: Write Terraform Files
      action: shell
      input:
        commands:
          - |
            cat > main.tf <<EOF
            provider "google" {
              credentials = "${SERVICE_ACCOUNT_KEY}"
              project     = "${PROJECT_ID}"
            }

            resource "google_project" "default" {
              name       = "Example GCP Project"
              project_id = "${PROJECT_ID}"
            }
            EOF
        env:
          PROJECT_ID: ${{ parameters.project_id }}
          SERVICE_ACCOUNT_KEY: ${{ parameters.service_account_key }}

    - id: terraform-init
      name: Terraform Init
      action: shell
      input:
        commands:
          - terraform init

    - id: terraform-apply
      name: Terraform Apply
      action: shell
      input:
        commands:
          - terraform apply -auto-approve
