apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-deployment
  title: Deploy Terraform
  description: Trigger a GitLab pipeline to deploy a Terraform project with dynamic variables
  tags:
    - terraform
    - gitlab
spec:
  owner: users
  type: service
  parameters:
    - title: Terraform Variables
      properties:
        parent:
          type: string
          title: Parent Organization (e.g., Organizations/123456)
        name:
          type: string
          title: Project Name
        gitlab_pipeline_url:
          type: string
          title: GitLab Pipeline Trigger URL
      required:
        - parent
        - name
        - gitlab_pipeline_url
  steps:
    - id: deploy
      name: Trigger GitLab Pipeline
      action: http:request
      input:
        url: ${{ parameters.gitlab_pipeline_url }}
        method: POST
        headers:
          PRIVATE-TOKEN: ${{ secrets.gitlab_token }}
        body:
          ref: main
          variables:
            TF_VAR_parent: ${{ parameters.parent }}
            TF_VAR_name: ${{ parameters.name }}
